charms = ['gatheringswarm', 'waywardcompass', 'grubsong', 'stalwartshell',
          'baldurshell', 'furyofthefallen', 'quickfocus', 'lifebloodheart',
          'lifebloodcore', 'defenderscrest', 'flukenest', 'thornsofagony',
          'markofpride', 'steadybody', 'heavyblow', 'sharpshadow',
          'sporeshroom', 'longnail', 'shamanstone', 'soulcatcher',
          'souleater', 'glowingwomb', 'fragileheart', 'fragilegreed',
          'fragilestrength', 'nailmastersglory', 'jonisblessing', 'shapeofunn',
          'hiveblood', 'dreamwielder', 'dashmaster', 'quickslash',
          'spelltwister', 'deepfocus', 'grubberflyselegy', 'kingsoul',
          'sprintmaster', 'dreamshield', 'weaversong', 'grimmchild', 'bluemothwings', 'antigravityamulet', 'lemmsstrength', 'floristsblessing', 'snailslash', 'snailsoul', 'shamanamp', 'nitrocrystal', 'crystalmaster', 'disinfectantflask', 'millibellesblessing', 'greedsong', 'marissasaudience', 'chaosorb', 'vespasvengeance']
